JWT_SECRET_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
JWT_EXPIRE_LENGTH: 36000000

PG_TOSS_PAYMENT_BASE_URL: https://api.tosspayments.com
PG_TOSS_PAYMENT_SECRET_KEY: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
PG_TOSS_PAYMENT_CONNECT_TIMEOUT: 15000
PG_TOSS_PAYMENT_READ_TIMEOUT: 60000
